import java.util.Scanner;

class Exception
{
public static void main(String[]args)
{

int x,y,answer;
Scanner sky = new Scanner(System.in);

int x =sky.nextInt();
int y =sky.nextInt();

try 
{

result = x/y;
System.out.println("The answer is: "+answer);
int arr[]=new int[5];
a[6]=19;
}
catch (ArithmaticException a)

{
System.out.println(a);

System.out.println("Denominator is zero");
}

catch (Exception b)

{
System.out.println(b);

System.out.println("Exception");
}
System.out.println("JAI SHREE RAM");
}
}